# Generated by Django 5.1.6 on 2025-03-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(default=0.0, help_text='Peso calculado mediante AHP')),
            ],
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Valor de comparación (por ejemplo: 1, 3, 5, 7, 9)')),
                ('criterion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_from', to='analysis.criterion')),
                ('criterion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_to', to='analysis.criterion')),
            ],
        ),
    ]
