# Generated by Django 5.1.6 on 2025-03-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(default=0.0, help_text='Peso calculado para el subcriterio')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='analysis.criterion')),
            ],
        ),
    ]
