# Generated by Django 5.1.6 on 2025-03-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_subcriterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCriterionComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Valor de comparación (por ejemplo: 1, 3, 5, 7, 9)')),
                ('subcriterion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomp_from', to='analysis.subcriterion')),
                ('subcriterion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomp_to', to='analysis.subcriterion')),
            ],
        ),
    ]
