# Generated by Django 5.1.6 on 2025-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_subcriterioncomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriterion',
            name='weight_global',
            field=models.FloatField(default=0.0, help_text='Peso global (criterio * subcriterio)'),
        ),
    ]
