# Generated by Django 5.1.6 on 2025-03-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_subcriterion_weight_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='weight',
        ),
    ]
