# Generated by Django 5.1.6 on 2025-03-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_criterion_description_remove_criterion_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriterion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcriterion',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='subcriterion',
            name='weight_global',
        ),
    ]
